### PR TITLE
Suppress uncaught `DOMException` error while upgrading `<marp-pre>` Web Component elements in Firefox

### LINKED ISSUE #370: Code block in HTML presentation issues Uncaught DOMException: Operation is not supported
### Version of Marp Tool

marp-vscode 2.8.0

### Operating System

macOS

### Environment

- VS Code (version 1.88)]
- MacOS Sonoma 14.4.1
- Mozilla Firefox (125.0.2 (64-bit))

### How to reproduce

Any code block defined in presentation:

`---`
`marp: true`
`---`

` ``` `
` ``` `

Presentation exported to HTML and viewed in mozilla.

### Expected behavior

No loading/console errors.

### Actual behavior

Presentation loads, but with errors. This is especially visible with a larger presentation and a mobile browser.

Browser console output:
```
Uncaught DOMException: Operation is not supported
    <anonymous> file:///Users/user/slides/test.html:14
    w file:///Users/vdangovas/user/slides/test.html:14
    w file:///Users/vdangovas/user/slides/test.html:14
    <anonymous> file:///Users/user/slides/test.html:14
    <anonymous> file:///Users/user/slides/[test.html:14](file:///Users/user/slides/test.html) test.html:14
    <anonymous> file:///Users/user/slides/test.html:14
    w file:///Users/user/slides/test.html:14
    w file:///Users/user/slides/test.html:14
    <anonymous> file:///Users/user/slides/test.html:14
    <anonymous> file:///Users/user/slides/test.html:14
```

Line 14 is `<script>!function()[...]`

### Additional information

Public instance with these errors: https://vainiusd.github.io/marp-cheatslides/

### PR DESCRIPTION
**Pull request by yhatt**
Fix #370.

This error is the error brought by Firefox while upgrading web components, and that is not affected to the subsequent browser script running on JavaScript main threads. Nevertheless, supressing errors is well-mannered.

- When updating the shadow root, we will check whether that is prepared.
- Known error `NotSupportedError` in Firefox will be simply suppressed.

### CODE REVIEW

File: test/custom-elements/browser.ts [hunk 1]
```diff
@@ -84,6 +84,34 @@ describe('The hydration script for custom elements', () => {
...
+      document.body.innerHTML = '<pre is="marp-pre">1</pre>'
+
+      jest.spyOn(console, 'error').mockImplementation(() => {})
+      jest
+        .spyOn(HTMLElement.prototype, 'attachShadow')
+        .mockImplementationOnce(() => {
+          throw new Error('Unknown error while attaching shadow')
+        })
+
+      expect(() => browser.applyCustomElements()).toThrow()
```
Comment (yhatt) [inline test/custom-elements/browser.ts:112]: This test does not pass due to browser error that cannot catch by JS main thread.
